# Create image based on Ubuntu 18.04
FROM ubuntu:bionic

##
# SEE THIS TUTORIAL FOR INSTALLATION TROUBLESHOOTING https://rdragos.github.io/2019/01/07/scale/
##

# install dependency
RUN apt-get -y update 
RUN apt-get -y upgrade
RUN apt-get -y install sudo
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y build-essential
RUN apt-get -y update 
RUN apt-get install -y libcrypto++6 
RUN apt-get install -y libcrypto++6-dbg 
RUN apt-get install -y libcrypto++-dev
RUN apt-get install -y python
RUN apt-get install -y libgmp3-dev
RUN apt-get install -y golang-go
RUN apt-get install -y psmisc
RUN apt-get install -y traceroute
RUN apt-get install -y nano
RUN apt-get install -y gzip

# needed by mpir
RUN apt-get install -y yasm 
RUN apt-get install -y m4

# config stuff
ENV mylocal "$HOME/local"
RUN mkdir -p ${mylocal}

# install MPIR 3.0.0
WORKDIR ${mylocal}
RUN curl -O "http://mpir.org/mpir-3.0.0.tar.bz2" \
    && tar xf mpir-3.0.0.tar.bz2 \
    && cd mpir-3.0.0 \
    && ./configure --enable-cxx --prefix="${mylocal}/mpir" \
    && make \
    && make check \
    && make install 

# install OpenSSL 1.1.0
WORKDIR $mylocal
RUN curl -O "https://www.openssl.org/source/openssl-1.1.0j.tar.gz" \
    && tar -xf openssl-1.1.0j.tar.gz \
    && cd openssl-1.1.0j \
    && ./config --prefix="${mylocal}/openssl" \
    && make \ 
    && make install

# install crypto++
WORKDIR ${mylocal}
RUN curl -O https://www.cryptopp.com/cryptopp800.zip
RUN unzip cryptopp800.zip -d cryptopp800
RUN cd cryptopp800
RUN make && make install PREFIX=${mylocal}/cryptopp


# update bashrc
ENV mylocal=$HOME/local

# export OpenSSL paths
ENV PATH="${mylocal}/openssl/bin/:${PATH}"
ENV C_INCLUDE_PATH="${mylocal}/openssl/include/:${C_INCLUDE_PATH}"
ENV CPLUS_INCLUDE_PATH="${mylocal}/openssl/include/:${CPLUS_INCLUDE_PATH}"
ENV LIBRARY_PATH="${mylocal}/openssl/lib/:${LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${mylocal}/openssl/lib/:${LD_LIBRARY_PATH}"

# export MPIR paths
ENV PATH="${mylocal}/mpir/bin/:${PATH}"
ENV C_INCLUDE_PATH="${mylocal}/mpir/include/:${C_INCLUDE_PATH}"
ENV CPLUS_INCLUDE_PATH="${mylocal}/mpir/include/:${CPLUS_INCLUDE_PATH}" 
ENV LIBRARY_PATH="${mylocal}/mpir/lib/:${LIBRARY_PATH}" 
ENV LD_LIBRARY_PATH="${mylocal}/mpir/lib/:${LD_LIBRARY_PATH}"

# export Crypto++ paths
ENV CPLUS_INCLUDE_PATH="${mylocal}/cryptopp/include/:${CPLUS_INCLUDE_PATH}"
ENV LIBRARY_PATH="${mylocal}/cryptopp/lib/:${LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${mylocal}/cryptopp/lib/:${LD_LIBRARY_PATH}"


# copy the code into the repo
COPY . /spdz_mpc
WORKDIR /spdz_mpc

RUN cp CONFIG CONFIG.mine
RUN echo "ROOT = $HOME/SCALE-MAMBA" >> CONFIG.mine
RUN echo "OSSL = ${mylocal}/openssl" >> CONFIG.mine

RUN make progs
RUN python2.7 compile.py Programs/star_action_1 
RUN python2.7 compile.py Programs/star_action_2